# Generated by Django 4.2.7 on 2023-11-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('team1Score', models.IntegerField()),
                ('team2Score', models.IntegerField()),
                ('tournament', models.CharField(max_length=100)),
                ('court', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('livestreamLink', models.CharField(max_length=300)),
                ('refereeCode', models.IntegerField()),
                ('style', models.CharField(max_length=100)),
            ],
        ),
    ]
