# Generated by Django 4.2.7 on 2023-11-22 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_matches_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matches',
            new_name='Match',
        ),
    ]
