# Generated by Django 4.2.7 on 2023-11-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_rename_matches_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='livestreamLink',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
