# Generated by Django 4.2.7 on 2023-12-12 20:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamid', models.AutoField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=100)),
                ('teamAcronym', models.CharField(max_length=10)),
                ('yearFounded', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('yearDisbanded', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)])),
                ('active', models.BooleanField(default=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.university')),
            ],
        ),
    ]
