# Generated by Django 4.2.7 on 2023-12-20 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='COURT',
            fields=[
                ('court_ID', models.AutoField(primary_key=True, serialize=False)),
                ('courtNumber', models.PositiveIntegerField(max_length=100)),
                ('livestreamed', models.BooleanField(default=False)),
                ('link', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
    ]
