# Generated by Django 4.2.7 on 2023-12-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0002_alter_court_courtnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
