# Generated by Django 4.2.7 on 2023-12-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('universityid', models.AutoField(primary_key=True, serialize=False)),
                ('universityName', models.CharField(max_length=100)),
                ('universityAcronym', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
