# Generated by Django 4.2.7 on 2024-01-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RULES',
            fields=[
                ('rules_ID', models.AutoField(primary_key=True, serialize=False)),
                ('minShotClock', models.IntegerField()),
                ('maxShotClock', models.IntegerField(blank=True, null=True)),
                ('numPlayers', models.IntegerField()),
                ('maxToMinPlayers', models.IntegerField(blank=True, null=True)),
                ('halfLength', models.IntegerField()),
                ('runningClockDiff', models.IntegerField()),
            ],
        ),
    ]
