# Generated by Django 4.2.7 on 2024-01-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='halfTimeouts',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rules',
            name='otTimeouts',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
