# Generated by Django 4.2.7 on 2023-12-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_team', '0002_remove_user_team_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_team',
            name='graphic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
