# Generated by Django 4.2.7 on 2023-12-20 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('season', '0002_rename_leagueid_season_league_and_more'),
        ('league', '0003_rename_leagueid_league_league_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LEAGUE_SEASON',
            fields=[
                ('league_Season_ID', models.AutoField(primary_key=True, serialize=False)),
                ('rules', models.CharField(max_length=100)),
                ('leagueID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
                ('seasonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='season.season')),
            ],
        ),
    ]
