# Generated by Django 4.2.7 on 2023-12-20 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league_season', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league_season',
            old_name='leagueID',
            new_name='league',
        ),
        migrations.RenameField(
            model_name='league_season',
            old_name='seasonID',
            new_name='season',
        ),
    ]
