# Generated by Django 4.2.7 on 2023-12-20 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_team_active'),
        ('league_season', '0002_rename_leagueid_league_season_league_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league_season',
            name='champion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
            preserve_default=False,
        ),
    ]
