# Generated by Django 4.2.7 on 2023-12-22 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league_season', '0003_league_season_champion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league_season',
            name='champion',
        ),
    ]
