# Generated by Django 4.2.7 on 2024-01-22 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league_season', '0006_league_season_rulebook_alter_league_season_rules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league_season',
            old_name='ruleBook',
            new_name='ruleBookLink',
        ),
        migrations.RemoveField(
            model_name='league_season',
            name='rules',
        ),
    ]
