# Generated by Django 4.2.7 on 2024-01-22 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
        ('league_season', '0007_rename_rulebook_league_season_rulebooklink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league_season',
            name='rules',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rules.rules'),
            preserve_default=False,
        ),
    ]
