# Generated by Django 4.2.7 on 2023-12-20 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('league', '0003_rename_leagueid_league_league_id'),
        ('event_type', '0001_initial'),
        ('season', '0003_remove_season_league'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVENT',
            fields=[
                ('event_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('graphic', models.CharField(blank=True, max_length=100, null=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_type.event_type')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='season.season')),
            ],
        ),
    ]
