# Generated by Django 4.2.7 on 2024-01-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_graphic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
