# Generated by Django 4.2.7 on 2023-12-20 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('league', '0003_rename_leagueid_league_league_id'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='USER_REF',
            fields=[
                ('user_ref_ID', models.AutoField(primary_key=True, serialize=False)),
                ('canRef', models.BooleanField(default=False)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
