# Generated by Django 4.2.7 on 2023-12-20 04:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LEAGUE',
            fields=[
                ('league_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=10)),
                ('yearFounded', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('graphic', models.CharField(blank=True, max_length=100, null=True)),
                ('altGraphic', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
