# Generated by Django 4.2.7 on 2023-12-20 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='league_ID',
            new_name='leagueID',
        ),
    ]
