# Generated by Django 4.2.7 on 2023-12-20 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_rename_league_id_league_leagueid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='leagueID',
            new_name='league_ID',
        ),
    ]
