# Generated by Django 4.2.7 on 2023-12-12 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0002_season_seasonname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='year',
            new_name='seasonYear',
        ),
        migrations.RemoveField(
            model_name='season',
            name='seasonName',
        ),
    ]
