# Generated by Django 4.2.7 on 2023-12-12 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('season', '0003_rename_year_season_seasonyear_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonTeam',
            fields=[
                ('seasonTeamid', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='season.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
        ),
    ]
