# Generated by Django 4.2.7 on 2023-12-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('matchid', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=100)),
                ('team1Score', models.PositiveIntegerField(default=0)),
                ('team2Score', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
