# Generated by Django 4.2.7 on 2023-12-20 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('match_type', '0001_initial'),
        ('court', '0003_alter_court_link'),
        ('user_ref', '0001_initial'),
        ('team', '0003_alter_team_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MATCH',
            fields=[
                ('match_ID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='court.court')),
                ('headRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_ref.user_ref')),
                ('match_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match_type.match_type')),
                ('officiatingTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officiatingTeam', to='team.team')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='team.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='team.team')),
            ],
        ),
    ]
