# Generated by Django 4.2.7 on 2023-12-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_alter_match_endtime_alter_match_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='endTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
