# Generated by Django 4.2.7 on 2023-12-20 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0003_alter_team_active'),
        ('match', '0003_alter_match_endtime_alter_match_starttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='POINT',
            fields=[
                ('point_ID', models.AutoField(primary_key=True, serialize=False)),
                ('pointNumber', models.PositiveIntegerField()),
                ('half', models.CharField(max_length=100)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('note', models.CharField(max_length=200)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.match')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
        ),
    ]
