# Generated by Django 4.2.7 on 2023-12-20 06:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('league', '0003_rename_leagueid_league_league_id'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TEAM',
            fields=[
                ('team_ID', models.AutoField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=100)),
                ('teamAcronym', models.CharField(max_length=10)),
                ('yearFounded', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('graphic', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BinaryField()),
                ('yearDisbanded', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)])),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
            ],
        ),
    ]
