# Generated by Django 4.2.7 on 2023-12-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
